files.c in current dirs and subdirs

diff --git a/run b/run
--- a/run
+++ b/run
@@ -2,35 +2,52 @@
 
 CFLAGS="-std=c11 -Wall -Wextra -Werror"
 
-# Check if the user provided a .c file
-if [ $# -ne 1 ]; then
-    echo "Usage: $0 <source_file.c>"
-    exit 1
-fi
+process_file(){
+	 # Get the input file and derive the test file name
+    SRC_FILE=$(basename "$1")
+    SRC_FULL="$1"
+    TEST_FILE="$HOME/tests/${SRC_FILE%.c}_test.c"
 
-# Get the input file and derive the test file name
-SOURCE_FILE="$1"
-TEST_FILE="$HOME/tests/${SOURCE_FILE%.c}_test.c"
+    # Check if the source file exists
+    if [ ! -f "$SRC_FULL" ]; then
+        echo "Error: Source file '$SRC_FULL' not found!"
+        exit 1
+    fi
 
-# Check if the source file exists
-if [ ! -f "$SOURCE_FILE" ]; then
-    echo "Error: Source file '$SOURCE_FILE' not found!"
-    exit 1
-fi
+    # Check if the corresponding test file exists
+    if [ ! -f "$TEST_FILE" ]; then
+        echo "Error: Test file '$TEST_FILE' not found!"
+        exit 1
+    fi
 
-# Check if the corresponding test file exists
-if [ ! -f "$TEST_FILE" ]; then
-    echo "Error: Test file '$TEST_FILE' not found!"
-    exit 1
-fi
+    # Compile the source and test files
+    gcc $CFLAGS "$SRC_FULL" "$TEST_FILE"
 
-# Compile the source and test files
-gcc $CFLAGS "$SOURCE_FILE" "$TEST_FILE"
+    # Check if the compilation was successful
+    if [ $? -eq 0 ]; then
+        ./a.out
+        rm ./a.out
+    else
+        echo "Compilation failed!"
+    fi
+}
 
-# Check if the compilation was successful
-if [ $? -eq 0 ]; then
-	./a.out
-	rm ./a.out
-else
-    echo "Compilation failed!"
+while getopts "h" arg; do
+  case $arg in
+    h)
+	  echo "Usage:"
+      printf "bash run <file.c>\t- run test for file.c\n"
+	  printf "bash run \t\t- run test for every c file in current dir and subdirs\n"
+      exit 0
+	  ;;
+  esac
+done
+
+if [ $# -eq 0 ]; then
+	find . -type f -name "*.c" | while read -r file; do
+		process_file "$file"
+	done
+elif [ $# -eq 1 ]; then
+	filename="$1"
+	process_file "$filename"
 fi
